### PR TITLE
fix: service name definition

### PR DESCRIPTION
**Pull request by JSahlberg42**
**Description**

Service definition points to fullname without "-http" prefix.

# Linked issue(s)
Relates #0000

**Checklist**

- [ ] Unit tests updated
- [ ] End user documentation updated

### Community Note

- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by M0NsTeRRR** [comment]
Hello,
Thanks for your PR, can you upgrade the patch version number in `Chart.yml` and run `helm-docs` to regenerate the `README.md` ?
Regards,

**Review by M0NsTeRRR — CHANGES_REQUESTED** [review]
Hello,
Thanks for your PR, can you upgrade the patch version number in `Chart.yml` and run `helm-docs` to regenerate the `README.md` ?
Regards,

**Comment by JSahlberg42** [comment]
Version number upgraded to 1.0.1 and `helm-docs` ran.

**Comment by M0NsTeRRR** [comment]
Thanks for your contribution !

**Pull request merged**
